services:
  - type: web
    name: backend-api
    env: python
    runtime: python-3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python create_tables.py && alembic stamp head && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_NO_CACHE_DIR
        value: 1
